apiVersion: v1
kind: Service

metadata:
  name: front-end-service
  namespace: front
spec:
  selector:
    app: front-end
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: metrics
    protocol: TCP
    port: 9113
    targetPort: 9113
  type: NodePort