apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
- name: app-config
  literals:
    - ENV=production
    - DEBUG=false

images:
  - name: goodbirdacr.azurecr.io/medical/front
    newTag: prod

patches:
- path: patch_deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: front-end-deployment
    namespace: front
    version: v1