apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- literals:
  - ENV=staging
  - DEBUG=false
  name: app-config

images:
- name: goodbirdacr.azurecr.io/medical/front
  newName: goodbirdacr.azurecr.io/medical/front
  newTag: prod-6

patches:
- path: patch_deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: front-end-deployment
    namespace: front
    version: v1
