apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  namespace: frontend
spec:
  template:
    spec:
      containers:
      - name: front-end-deployment
        image: goodbirdacr.azurecr.io/medical/front:dev-latest
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"